import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import Image from '@/components/Image';
import Titulo from '@/components/Titulo';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Titulo 
        titulo='Ejercicio de la clase 9'
      />
      <Image />
    </>
  )
}
